// Generated by delombok at Fri Aug 13 16:07:39 CEST 2021
package de.kosit.xmlmutate.context;

import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;

public class ProjectInfo {
    private String version;
    private String buildTimestamp;
    private String name;
    private String description;

    public ProjectInfo() {
        final Properties p = new Properties();
        try (InputStream in = ProjectInfo.class.getClassLoader().getResourceAsStream("version.properties")) {
            p.load(in);
            this.buildTimestamp = p.getProperty("maven_build_timestamp");
            this.version = p.getProperty("project_version");
            this.name = p.getProperty("project_name");
            this.description = p.getProperty("project_description");
        } catch (final IOException e) {
            throw new IllegalStateException("Can not initialize version information");
        }
    }

    @java.lang.SuppressWarnings("all")
    public String getVersion() {
        return this.version;
    }

    @java.lang.SuppressWarnings("all")
    public String getBuildTimestamp() {
        return this.buildTimestamp;
    }

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    public String getDescription() {
        return this.description;
    }
}
