// Generated by delombok at Fri Aug 13 16:07:39 CEST 2021
package de.kosit.xmlmutate.runner;

import de.kosit.xmlmutate.mutation.NamedTemplate;
import de.kosit.xmlmutate.mutation.Schematron;
import de.kosit.xmlmutate.report.ReportGenerator;
import de.kosit.xmlmutate.report.TextReportGenerator;
import de.kosit.xmlmutate.runner.MarkMutationAction.RemoveCommentAction;
import java.io.PrintWriter;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import javax.xml.validation.Schema;

/**
 * Contains whole configuration for a {@link MutationRunner} including all Actions.
 *
 * @author Andreas Penski
 */
public class RunnerConfig {

    public static class Builder {
        private final RunnerConfig config = new RunnerConfig();
        public RunMode mode = RunMode.ALL;

        public static Builder forDocuments(final List<Path> docs) {
            final Builder b = new Builder();
            b.config.setDocuments(docs);
            return b;
        }

        public static Builder forDocuments(final Path doc) {
            return forDocuments(Collections.singletonList(doc));
        }

        public Builder mode(final RunMode mode) {
            this.mode = mode;
            return this;
        }

        public Builder targetFolder(final Path p) {
            this.config.setTargetFolder(p);
            return this;
        }

        public Builder checkSchema(final Schema schema) {
            this.config.setSchema(schema);
            return this;
        }

        public Builder reportWith(final ReportGenerator generator) {
            this.config.setReportGenerator(generator);
            return this;
        }

        public Builder withExecutor(final ExecutorService service) {
            this.config.setExecutorService(service);
            return this;
        }

        public Builder checkSchematron(final List<Schematron> rules) {
            this.config.setSchematronRules(rules);
            return this;
        }

        public Builder useTransformations(final List<NamedTemplate> templates) {
            this.config.setTemplates(templates);
            return this;
        }

        public Builder withFailureMode(final FailureMode failureMode) {
            this.config.setFailureMode(failureMode);
            return this;
        }

        public Builder withSavingMode(final SavingMode savingMode) {
            this.config.setSavingMode(savingMode);
            return this;
        }

        public Builder withIgnoreSchemaInvalidity(final boolean ignoreSchemaInvalidity) {
            this.config.setIgnoreSchemaInvalidity(ignoreSchemaInvalidity);
            return this;
        }

        public Builder saveParsing(final boolean saveParsingMode) {
            this.config.setSaveParsing(saveParsingMode);
            return this;
        }

        public Builder saveSvrl(final boolean saveSvrlMode) {
            this.config.setSaveSvrl(saveSvrlMode);
            return this;
        }

        public RunnerConfig build() {
            this.config.getActions().add(new MarkMutationAction.InsertCommentAction());
            this.config.getActions().add(new MutateAction());
            this.config.getActions().add(new SerializeAction(this.config.getTargetFolder()));
            this.config.getActions().add(new ValidateAction(this.config.getSchema(), this.config.getSchematronRules(), this.config.getTargetFolder()));
            this.config.getActions().add(new EvaluateSchematronExpectationsAction());
            this.config.getActions().add(new ResetAction());
            this.config.getActions().add(new RemoveCommentAction());
            if (this.config.getExecutorService() == null) {
                this.config.setExecutorService(Executors.newFixedThreadPool(Runtime.getRuntime().availableProcessors()));
            }
            return this.config;
        }
    }

    /**
     * Target directory for outputs
     */
    private Path targetFolder;
    private List<Path> documents;
    private Schema schema;
    private ReportGenerator reportGenerator = new TextReportGenerator(new PrintWriter(System.out));
    private List<RunAction> actions = new ArrayList<>();
    private List<Schematron> schematronRules = new ArrayList<>();
    private List<NamedTemplate> templates;
    private ExecutorService executorService;
    private FailureMode failureMode;
    private SavingMode savingMode = SavingMode.SINGLE;
    private boolean saveParsing;
    private boolean saveSvrl;
    private boolean ignoreSchemaInvalidity;

    public void addTemplate(final String name, final Path transform) {
        if (this.templates == null) {
            this.templates = new ArrayList<>();
        }
        this.templates.add(new NamedTemplate(name, transform.toUri()));
    }

    /**
     * Target directory for outputs
     */
    public Path getTargetFolder() {
        return this.targetFolder;
    }

    public List<Path> getDocuments() {
        return this.documents;
    }

    public Schema getSchema() {
        return this.schema;
    }

    public ReportGenerator getReportGenerator() {
        return this.reportGenerator;
    }

    public List<RunAction> getActions() {
        return this.actions;
    }

    public List<Schematron> getSchematronRules() {
        return this.schematronRules;
    }

    public List<NamedTemplate> getTemplates() {
        return this.templates;
    }

    public ExecutorService getExecutorService() {
        return this.executorService;
    }

    public FailureMode getFailureMode() {
        return this.failureMode;
    }

    public SavingMode getSavingMode() {
        return this.savingMode;
    }

    public boolean isSaveParsing() {
        return this.saveParsing;
    }

    public boolean isSaveSvrl() {
        return this.saveSvrl;
    }

    public boolean isIgnoreSchemaInvalidity() {
        return this.ignoreSchemaInvalidity;
    }

    /**
     * Target directory for outputs
     */
    public void setTargetFolder(final Path targetFolder) {
        this.targetFolder = targetFolder;
    }

    public void setDocuments(final List<Path> documents) {
        this.documents = documents;
    }

    public void setSchema(final Schema schema) {
        this.schema = schema;
    }

    public void setReportGenerator(final ReportGenerator reportGenerator) {
        this.reportGenerator = reportGenerator;
    }

    public void setActions(final List<RunAction> actions) {
        this.actions = actions;
    }

    public void setSchematronRules(final List<Schematron> schematronRules) {
        this.schematronRules = schematronRules;
    }

    public void setTemplates(final List<NamedTemplate> templates) {
        this.templates = templates;
    }

    public void setExecutorService(final ExecutorService executorService) {
        this.executorService = executorService;
    }

    public void setFailureMode(final FailureMode failureMode) {
        this.failureMode = failureMode;
    }

    public void setSavingMode(final SavingMode savingMode) {
        this.savingMode = savingMode;
    }

    public void setSaveParsing(final boolean saveParsing) {
        this.saveParsing = saveParsing;
    }

    public void setSaveSvrl(final boolean saveSvrl) {
        this.saveSvrl = saveSvrl;
    }

    public void setIgnoreSchemaInvalidity(final boolean ignoreSchemaInvalidity) {
        this.ignoreSchemaInvalidity = ignoreSchemaInvalidity;
    }
}
