// Generated by delombok at Fri Aug 13 16:07:39 CEST 2021
package de.kosit.xmlmutate.runner;

import de.kosit.xmlmutate.mutation.NameGenerator;
import de.kosit.xmlmutate.mutation.SequenceNameGenerator;
import de.kosit.xmlmutate.mutator.MutatorRegistry;

/**
 * Mutator-side service locator. Holds dependencies that produce mutated documents
 * (mutator registry, name generator, template repository) and must remain free of
 * any validation-stack initialization. Validation services live in
 * {@link ValidatorServices}.
 *
 * @author Andreas Penski
 */
public final class Services {
    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(Services.class);
    private static final MutatorRegistry registry;
    private static final NameGenerator nameGenerator = new SequenceNameGenerator();
    private static final TemplateRepository templateRepository;

    private Services() {
    }

    static {
        log.debug("Initializing mutator services");
        templateRepository = new TemplateRepository();
        registry = MutatorRegistry.getInstance();
    }

    public static MutatorRegistry getRegistry() {
        return registry;
    }

    public static NameGenerator getNameGenerator() {
        return nameGenerator;
    }

    public static TemplateRepository getTemplateRepository() {
        return templateRepository;
    }
}
