// Generated by delombok at Fri Aug 13 16:11:22 CEST 2021
package de.init.kosit.commons;

import org.slf4j.Logger;

/**
 * Simple Hilfsklasse zum Weiterreichen von Syntax-Fehlern.
 *
 * @author Andreas Penski (]init[ AG)
 */
public final class SyntaxError {
    private Severity severity;
    private String message;
    private String source;
    private int rowNumber;
    private int columnNumber;

    public Severity getSeverity() {
        return this.severity;
    }

    public void setSeverity(final Severity severity) {
        this.severity = severity;
    }

    public String getMessage() {
        return this.message;
    }

    public void setMessage(final String message) {
        this.message = message;
    }

    public String getSource() {
        return this.source;
    }

    public void setSource(final String source) {
        this.source = source;
    }

    public int getRowNumber() {
        return this.rowNumber;
    }

    public void setRowNumber(final int rowNumber) {
        this.rowNumber = rowNumber;
    }

    public int getColumnNumber() {
        return this.columnNumber;
    }

    public void setColumnNumber(final int columnNumber) {
        this.columnNumber = columnNumber;
    }

    public void log(final Logger logger) {
        final String msgTemplate = "{} in {} at row {} at pos {}";
        final Object[] params = {getMessage(), getSource(), getRowNumber(), getColumnNumber()};
        if (getSeverity() == Severity.SEVERITY_WARNING) {
            logger.warn(msgTemplate, params);
        } else {
            logger.error(msgTemplate, params);
        }
    }

    @Override
    public String toString() {
        return getSeverity().name() + " " + getMessage() + " At row " + getRowNumber() + " at pos " + getColumnNumber();
    }
}
