// Generated by delombok at Fri Aug 13 16:11:22 CEST 2021
package de.init.kosit.commons.schematron;

import java.net.URI;

import org.oclc.purl.dsdl.svrl.SchematronOutput;
import org.w3c.dom.Document;

import de.init.kosit.commons.transform.ExecutableRepository;
import de.init.kosit.commons.transform.Transform;
import de.init.kosit.commons.transform.TransformationService;
import net.sf.saxon.s9api.XsltExecutable;

/**
 * Schematron
 *
 * @author Andreas Penski
 */
public class SchematronService {
    private final ExecutableRepository executableRepository;
    private final TransformationService transformService;

    public SchematronService(final ExecutableRepository executableRepository, final TransformationService transformService) {
        this.executableRepository = executableRepository;
        this.transformService = transformService;
    }

    /**
     * @param schematron URI
     * @param document XML Document
     * @return SVRL
     */
    public SchematronOutput validate(final URI schematron, final Document document) {
        final Transform<SchematronOutput> t = Transform.create(getExecutable(schematron)).convertTo(SchematronOutput.class).build();
        return transformService.transform(t, document).getObject();
    }

    private XsltExecutable getExecutable(final URI uri) {
        return executableRepository.createExecutable(uri, null);
    }
}
