// Generated by delombok at Fri Aug 13 16:07:39 CEST 2021
package de.kosit.xmlmutate.mutator;

import java.util.Collections;
import java.util.List;

import javax.annotation.Nonnull;

import de.kosit.xmlmutate.mutation.Mutation;
import de.kosit.xmlmutate.mutation.MutationConfig;
import de.kosit.xmlmutate.mutation.MutationContext;
import de.kosit.xmlmutate.mutation.MutationGenerator;
import de.kosit.xmlmutate.runner.Services;

/**
 * Default generator.  It is called when a mutator is not in need of an special generator
 *
 * @author Andreas Penski
 */
public class DefaultMutationGenerator implements MutationGenerator {
    public static final String NAME = DefaultMutationGenerator.class.getSimpleName();

    @Override
    public List<Mutation> generateMutations(@Nonnull final MutationConfig config, @Nonnull final MutationContext context) {
        if (config == null) {
            throw new java.lang.NullPointerException("config is marked non-null but is null");
        }
        if (context == null) {
            throw new java.lang.NullPointerException("context is marked non-null but is null");
        }
        // Get first name of name list of mutator
        final Mutator mutator = Services.getRegistry().getMutator(config.getMutatorName());
        final Mutation m = new Mutation(context, Services.getNameGenerator().generateName(context.getDocumentName(), mutator.getPreferredName(), null), config, mutator);
        return Collections.singletonList(m);
    }

    @Override
    public List<String> getNames() {
        return Collections.singletonList(NAME);
    }

    @Override
    public String getPreferredName() {
        return getNames().stream().findFirst().orElseThrow(IllegalStateException::new);
    }

    @java.lang.SuppressWarnings("all")
    public DefaultMutationGenerator() {
    }
}
