// Generated by delombok at Fri Aug 13 16:07:39 CEST 2021
package de.kosit.xmlmutate.mutator;

import de.init.kosit.commons.util.NamedError;

/**
 * @author Andreas Penski
 */
public enum ErrorCode implements NamedError {
    TRANSFORM_ERROR("Error while transforming: {0}"), WHITESPACE_VARIATION_UNKNOWN("No whitespace mutator variation found with number: {0}"), STRUCTURAL_MISMATCH("Structural mismatch: {0}"), CONFIGURATION_ERRROR("Configuration error: {0}");
    private final String template;

    @java.lang.SuppressWarnings("all")
    private ErrorCode(final String template) {
        this.template = template;
    }

    @java.lang.SuppressWarnings("all")
    public String getTemplate() {
        return this.template;
    }
}
