// Generated by delombok at Fri Aug 13 16:07:39 CEST 2021
package de.kosit.xmlmutate.mutator;

import de.kosit.xmlmutate.mutation.MutationConfig;
import de.kosit.xmlmutate.mutation.MutationContext;
import java.util.Arrays;
import java.util.List;

/**
 * Simple mutator which does not make any changes to the documents.
 * Purpose is to check schematron assertions of the given document.
 *
 * @author Andreas Penski
 */
public class IdentityMutator implements Mutator {
    @java.lang.SuppressWarnings("all")
    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(IdentityMutator.class);

    @Override
    public List<String> getNames() {
        return Arrays.asList("identity", "noop");
    }

    @Override
    public String getPreferredName() {
        return getNames().stream().findFirst().get();
    }

    @Override
    public void mutate(MutationContext context, MutationConfig config) {
        log.debug("Mutating e.g. do \'nothing\'");
    }
}
