// Generated by delombok at Fri Aug 13 16:11:22 CEST 2021
package de.init.kosit.commons.artefact;

import java.net.URI;

/**
 * Eine Datei in eingelesener Form.
 *
 * @author apenski
 */
public class Artefact {
    private final byte[] content;
    private final String name;
    private final URI uri;
    private final ArtefactType type;
    private final String mimeType;
    /**
     * Extension der Datei und gibt über die Information des MIME-Types hinaus Detail zu den bereitgestellten Dateien.
     * Beispielsweise können unter dem MIME-Type "XML" die Formate WSDL, XML Schema-Definitionen,
     * Genericode etc. bereitgestellt werden.
     */
    private final String format;

    @java.lang.SuppressWarnings("all")
    public byte[] getContent() {
        return this.content;
    }

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    public URI getUri() {
        return this.uri;
    }

    @java.lang.SuppressWarnings("all")
    public ArtefactType getType() {
        return this.type;
    }

    @java.lang.SuppressWarnings("all")
    public String getMimeType() {
        return this.mimeType;
    }

    /**
     * Extension der Datei und gibt über die Information des MIME-Types hinaus Detail zu den bereitgestellten Dateien.
     * Beispielsweise können unter dem MIME-Type "XML" die Formate WSDL, XML Schema-Definitionen,
     * Genericode etc. bereitgestellt werden.
     */
    @java.lang.SuppressWarnings("all")
    public String getFormat() {
        return this.format;
    }

    @java.lang.SuppressWarnings("all")
    public Artefact(final byte[] content, final String name, final URI uri, final ArtefactType type, final String mimeType, final String format) {
        this.content = content;
        this.name = name;
        this.uri = uri;
        this.type = type;
        this.mimeType = mimeType;
        this.format = format;
    }
}
