// Generated by delombok at Fri Aug 13 16:11:22 CEST 2021
package de.init.kosit.commons.validate;

import de.init.kosit.commons.util.NamedMessage;

/**
 * Spezifischen Fehler bei der Validierung von XML Daten.
 *
 * @author apenski
 */
public enum ErrorCode implements NamedMessage {
    VALIDATION_ERROR("Technischer Fehler bei der Validierung gemäß Schema");
    private final String template;

    ErrorCode(final String template) {
        this.template = template;
    }

    public String getTemplate() {
        return this.template;
    }
}
