// Generated by delombok at Fri Aug 13 16:11:22 CEST 2021
package de.init.kosit.commons.normalize;

import java.util.Collection;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

import de.init.kosit.commons.artefact.Artefact;
import de.init.kosit.commons.artefact.ArtefactType;

/**
 * Eine Zusammenfassung von Modell-Definition und Referenzen, also benutzte Modelle und Imports.
 *
 * @author apenski
 */
public class Model extends AbstractNormalized {
    private Artefact main;

    @Nullable
    public final Artefact getMain() {
        return this.main;
    }

    public final void setMain(@Nullable final Artefact main) {
        this.main = main;
    }

    /**
     * lifert alle Artefacts(main Artefact und alle Referenzen), die zu diesem Model gehören.
     *
     * @return alle Artefacts, die zu dem Modell gehören.
     */
    @Override
    public Collection<Artefact> getArtefacts() {
        final Collection<Artefact> a = super.getArtefacts();
        if (getMain() != null) {
            a.add(getMain());
        }
        return a;
    }

    /**
     * Fügt ein Artefact zum Model hinzu.
     *
     * @param artefact
     */
    @Override
    public void addArtefact(@Nonnull final Artefact artefact) {
        if (artefact.getType() == ArtefactType.MODEL) {
            setMain(artefact);
        } else {
            super.addArtefact(artefact);
        }
    }
}
